[package]
name = "prettify_pinyin"
edition = "2021"
version = "1.1.2"
authors = ["Preston Wang-Stosur-Bassett <p.wanstobas@gmail.com>"]
description = "Turn tone numbers into tone marks"
repository = "https://github.com/sotch-pr35mac/prettify_pinyin"
readme = "README.md"
keywords = ["pinyin", "chinese", "hanzi"]
categories = ["localization", "value-formatting"]
license = "MIT"
